server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.96.16.194:3306/finalwork?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

mybatis:
  type-aliases-package: com.ha5fun.finalwork.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


